services:
  # BASE DE DATOS
  db:
    image: mysql:8.0
    container_name: limenita_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Autoejecuta tu script SQL al iniciar por primera vez
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  # BACKEND (Node.js)
  backend:
    build: ./backend
    container_name: limenita_api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

volumes:
  db_data: